"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
# # Get environment - defaults to 'development' for local work
# ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'development')

# if ENVIRONMENT == 'production':
#     # In production, these MUST be set as environment variables
#     SECRET_KEY = os.environ['DJANGO_SECRET_KEY']  # Will raise KeyError if not set
#     DEBUG = False  # Always False in production
# else:
#     # Development fallbacks
#     SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
#     DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ENVIRONMENT = 'production'
SECRET_KEY = "django-insecure-94+6orem9k^x4@6gc8+!ukyxsx-7)uh&uf!z8d2@o2e07k^%d#"
DEBUG = False

ALLOWED_HOSTS = [
    'drbot-onboarding-ftdtgvhpfmebdycm.canadacentral-01.azurewebsites.net',  # Actual Azure domain
    'drbot-onboarding.azurewebsites.net',  # DR Bot Azure Web App domain
    '169.254.129.2',  # Azure internal services
    'localhost',  # For local development
    '127.0.0.1',  # For local development
]

# CSRF settings for Azure deployment
CSRF_TRUSTED_ORIGINS = [
    'https://drbot-onboarding-ftdtgvhpfmebdycm.canadacentral-01.azurewebsites.net',
    'https://drbot-onboarding.azurewebsites.net',
    'https://*.azurewebsites.net',  # Covers any Azure subdomain variations
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Azure-specific settings
if ENVIRONMENT == 'production':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Azure handles SSL termination
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
